### ISSUE TITLE
Failed to backup world(Minecraft 1.16.5)

### ISSUE THREAD

**Issue by 111inhistory** [DichuuCraft/Fibersync#1]
I tried to use this mod to backup my server saves,but it failed to copy files for it cannot copy session.lock
Log below

[17:52:28] [main/INFO]: Loading for game Minecraft 1.16.5
[17:52:29] [main/INFO]: [FabricLoader] Loading 4 mods:
	- fabricloader@0.11.6
	- fibersync@1.16.5-0.3
	- java@11
	- minecraft@1.16.5
[17:52:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/server/server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[17:52:55] [main/INFO]: Environment: authHost='https://mcskin.littleservice.cn/api/yggdrasil/authserver', accountsHost='http://127.0.0.1:6088/https/api.mojang.com', sessionHost='http://127.0.0.1:6088/https/sessionserver.mojang.com', servicesHost='http://127.0.0.1:6088/https/api.minecraftservices.com', name='PROD'
[17:53:01] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:53:01] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:53:01] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:53:01] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:53:01] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:53:01] [main/INFO]: Reloading ResourceManager: Default
[17:53:05] [Worker-Main-11/INFO]: Loaded 7 recipes
[17:53:07] [Worker-Main-11/INFO]: Loaded 927 advancements
[17:53:14] [Server thread/INFO]: Starting minecraft server version 1.16.5
[17:53:14] [Server thread/INFO]: Loading properties
[17:53:14] [Server thread/INFO]: Default game type: SURVIVAL
[17:53:14] [Server thread/INFO]: Generating keypair
[17:53:15] [Server thread/INFO]: Starting Minecraft server on *:25565
[17:53:15] [Server thread/INFO]: Using default channel type
[17:53:21] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[17:53:21] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[17:53:21] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[17:53:21] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[17:53:21] [Server thread/INFO]: Preparing level "world"
[17:53:21] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:26] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:27] [Server thread/INFO]: Preparing spawn area: 0%
[17:53:27] [Server thread/INFO]: Preparing spawn area: 13%
[17:53:31] [Server thread/INFO]: Time elapsed: 9431 ms
[17:53:31] [Server thread/INFO]: Done (10.103s)! For help, type "help"
[17:53:31] [Server thread/INFO]: Starting remote control listener
[17:53:31] [Server thread/INFO]: Thread RCON Listener started
[17:53:31] [Server thread/INFO]: RCON running on 0.0.0.0:25575
[17:53:37] [Server thread/INFO]: Unknown or incomplete command, see below for error
[17:53:37] [Server thread/INFO]: fs<--[HERE]
[17:53:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[17:53:44] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[17:53:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[17:53:44] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:53:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[17:53:44] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:53:44] [Server thread/INFO]: [Fibersync] Server: 正在创建备份b1
[17:53:44] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3808ms or 76 ticks behind
[17:53:44] [ForkJoinPool.commonPool-worker-3/INFO]: world dir: .\world\.
[17:53:46] [ForkJoinPool.commonPool-worker-3/INFO]: Copying file: 10%
[17:53:47] [ForkJoinPool.commonPool-worker-3/INFO]: Copying file: 20%
[17:53:48] [ForkJoinPool.commonPool-worker-3/INFO]: Copying file: 30%
[17:53:49] [ForkJoinPool.commonPool-worker-3/INFO]: Copying file: 40%
[17:53:49] [ForkJoinPool.commonPool-worker-3/INFO]: Copying file: 50%
[17:53:50] [ForkJoinPool.commonPool-worker-3/INFO]: Copying file: 60%
[17:53:51] [ForkJoinPool.commonPool-worker-3/INFO]: Copying file: 70%
[17:53:52] [ForkJoinPool.commonPool-worker-3/INFO]: Copying file: 80%
[17:53:52] [ForkJoinPool.commonPool-worker-3/INFO]: Copying file: 90%
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: java.nio.file.FileSystemException: .\world\.\session.lock -> config\fibersync\backups\world\b1\world\session.lock: 另一个程序已锁定文件的一部分，进程无法访问。

[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:202)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:283)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.copy(Files.java:1295)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at com.hadroncfy.fibersync.util.copy.FileCopier.run(FileCopier.java:93)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at com.hadroncfy.fibersync.backup.BackupEntry.saveBackup(BackupEntry.java:69)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at com.hadroncfy.fibersync.command.task.BaseTask.lambda$doBackup$0(BaseTask.java:79)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[17:53:53] [ForkJoinPool.commonPool-worker-3/INFO]: [Fibersync] Server: 备份失败：java.nio.file.FileSystemException: .\world\.\session.lock -> config\fibersync\backups\world\b1\world\session.lock: 另一个程序已锁定文件的一部分，进程无法访问。

**Comment by Hadron67** [comment]
Should be fixed by https://github.com/DichuuCraft/Fibersync/commit/5f5f593340e1c2f4ec80bf8de71903e9007e432b

**Comment by Hadron67** [comment]
Please reopen this if the problem persists
